### ISSUE TITLE
Moonbeam Alpha?

### ISSUE THREAD

**Issue by corrie-sloot** [oceanprotocol/ocean.js-cli#1]
Can Moonbean alpha be added to the `ConfigHelper().getConfig()` function?

I think all the values should be in [ocean.js](https://github.com/oceanprotocol/ocean.js/blob/92b4be0dce525cc1016af75f6792a75620a54247/src/utils/ConfigHelper.ts)?

**Comment by alexcos20** [comment]
We bumped ocean.js to latest, so it works now on moonbeam alpha as well
